INSERT INTO cuisine_classification (name)
VALUES
("breakfast"),
("lunch"),
("dinner");


INSERT INTO restaurant_cuisine (restaurantId, ClassificationID, name, ImageURL) VALUES
(1, 1, "Egg Benedicts", "Benedicts.png"),
(1, 1, "The Breakfast Wrap", "b- wrap.png"),
(1, 1, "Avocado Toast", "avocado.png"),
(1, 1, "Spicy Honey Fried Chicken Sandwich", "Chicken-Sandwich.jpg"),
(2, 1, "Fresh Strawberry Nutella Tostada", "strawberry.png"),
(2, 1, "Grilled Three Cheese And Ham", "ham&cheese.png"),
(2, 1, "Herb Roasted Chicken", "herb.png"),
(3, 1, "Carrot-Pumpkin Soup", "Carrot-Soup.jpg"),
(3, 1, "Strawberry Waffle & Bacon", "bacon-waffle.jpg"),
(3, 1, "Power Salad", "Power Salad.jpg"),
(4, 1, "Skillet Omelet", "Skillet Omelet.jpg"),
(4, 1, "Tex Mex", "Tex Mex.jpg"),
(4, 1, "Spinach Mushroom ", "Spinach Mushroom.jpg"),
(5, 1, "Avocado, Bacon, Pepper Jack", " Pepper Jack.jpg"),
(5, 1, "Fried Mozzarella", "Fried Mozzarella.jpg"),
(6, 1, "Santa Fe Chicken Salad", "santafechickensalad.jpg"),
(7, 1, "Meatball Parm Sandwich", "Meatball Parm Sandwich.jpg"),

(8, 2, "Creamy Beef Salpicado", "beef.jpg"),
(9, 2, "Honey Garlic B.F. Chicken", "honey.jpg"),
(9, 2, "Spicy Chicken Salpicao", "spicy.jpg"),
(10, 2, "Beef Pot Roast Ranchero", "pot.jpg"),
(11, 2, "Cajun Rib-eye Steak", "steak.jpg"),
(11, 2, "Shrimp Scampi", "shrimp.png"),
(12, 2, "Chicken Fettuccine Alfredo", "pasta.png"),
(13, 2, "Grilled-Octopus", "Grilled-Octopus.jpg"),
(14, 2, "Chicken Giovanni", "Chicken Giovanni.jpg"),
(15, 2, "Crab Cakes Fried", "Crab Cakes Fried.jpg"),
(16, 2, "Fried Jumbo Shrimp", "Fried Jumbo Shrimp.jpg"),
(17, 2, "Linguine Al Cartoccio", "Linguine Al Cartoccio.jpg"),
(18, 2, "Ln Chicken Parma", "Ln Chicken Parma.jpg"),
(18, 2, "Ln Crabcake", "Ln Crabcake.jpg"),
(33, 2, "Buffalo Chicken Wrap", "Buffalo Chicken Wrap.jpg"),
(34, 2, "Thai Shrimp Wrap", "Thai Shrimp Wrap.jpg"),

(35, 3, "Rib Eye Steak", "Rib-Eye-Steak.jpg"),
(36, 3, "Crock Pot Beef and Noodles", "noodles.jpg"),
(37, 3, "Buffalo Cream Cheese Wings", "wings.jpg"),
(38, 3, "Crock Pot Beef and Noodles", "noodles.jpg"),
(39, 3, "Skill Thighset Teriyaki Chicken", "teriyaki.jpg"),
(40, 3, "Beef Pot Roast Ranchero", "salmon.jpg"),
(41, 3, "Unstuffed Cabbage Roll Soup", "soup.jpg"),
(42, 3, "Mandarin Chicken", "mandarin.jpeg"),
(43, 3, "Chicken Bruschetta", "Chicken Bruschetta.jpg"),
(44, 3, "Linguini and Meatballs", "Linguini and Meatballs.png"),
(45, 3, "Stuffed Shells", " Stuffed Shells.jpg"),
(46, 3, "Penne Alla Vodka", "Penne Alla Vodka.jpg"),
(47, 3, "Filet Mignon", "Filet Mignon.jpg"),
(48, 3, "Filet& Crab Cake Duet", "Filet& Crab Cake Duet.jpg"),
(49, 3, "Broiled Scallops", "Broiled Scallops.jpg"),
(50, 3, "Br Seafood Combo", "Br Seafood Combo.jpg"),
(18, 3, "Scallop Delight", "Scallop Delight.jpg");